### ISSUE TITLE
Could not compile on ubuntu 22.04

### ISSUE THREAD

**Issue by japinli** [phillbaker/pg_migrate#1]
Hi,

Recently, I got the pg_migrate could not be compiled as follows:

```
pgut/pgut-fe.c: In function ‘get_username’:
pgut/pgut-fe.c:652:14: warning: implicit declaration of function ‘getpwuid’; did you mean ‘geteuid’? [-Wimplicit-function-declaration]
  652 |         pw = getpwuid(geteuid());
      |              ^~~~~~~~
      |              geteuid
pgut/pgut-fe.c:652:12: warning: assignment to ‘struct passwd *’ from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
  652 |         pw = getpwuid(geteuid());
      |            ^
pgut/pgut-fe.c:653:23: error: invalid use of undefined type ‘struct passwd’
  653 |         ret = (pw ? pw->pw_name : NULL);
      |                       ^~
make[1]: *** [/home/japin/Codes/postgres/build/pg/lib/pgxs/src/makefiles/../../src/Makefile.global:962: pgut/pgut-fe.o] Error 1
make[1]: Leaving directory '/home/japin/Codes/pg-extensions/pg_migrate/bin'
make: *** [Makefile:35: all] Error 2
```

It seems to have forgotten to include the header files, here is a patch for this.

```diff
diff --git a/bin/pgut/pgut-fe.c b/bin/pgut/pgut-fe.c
index 56262fa..a0e3de0 100644
--- a/bin/pgut/pgut-fe.c
+++ b/bin/pgut/pgut-fe.c
@@ -16,6 +16,11 @@
 #include <getopt_long.h>
 #endif

+#ifndef WIN32
+#include <sys/types.h>
+#include <pwd.h>
+#endif
+
 char	   *dbname = NULL;
 char	   *host = NULL;
 char	   *port = NULL;
```

**Comment by phillbaker** [comment]
Hi, thanks for the patch!
